import React from 'react';
import ShortcodeParser from './ShortcodeParser';
import BlockRenderer from './BlockRenderer';

interface WordPressRendererProps {
  content: string | any[];
  context?: Record<string, any>;
}

/**
 * Strips embedded JSON-LD script tags from WordPress HTML content.
 * WordPress pages may contain their own structured data that conflicts
 * with the schemas generated by our Next.js schema components.
 */
function stripEmbeddedSchemas(html: string): string {
  return html.replace(/<script\s+type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi, '');
}

export default function WordPressRenderer({ content, context }: WordPressRendererProps) {
  if (!content) return null;

  if (typeof content === 'string') {
    const sanitized = stripEmbeddedSchemas(content);
    return <ShortcodeParser html={sanitized} context={context} />;
  }

  if (Array.isArray(content)) {
    return <BlockRenderer blocks={content} context={context} />;
  }

  return null;
}
