// Service Categories Configuration for Henotic Diagnostics PSEO Platform
// Groups all 303 services into logical, SEO-optimized diagnostic categories

export interface ServiceCategory {
  id: string;
  title: string;
  description: string;
  icon: string;
  services: string[];
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "diagnostic-services",
    title: "Diagnostic Services",
    description:
      "NABL-accredited diagnostic center services including medical imaging, radiology, pathology labs, and comprehensive diagnostic imaging infrastructure for accurate disease detection and monitoring.",
    icon: "Building2",
    services: [
      "diagnostic-center",
      "medical-imaging-center",
      "radiology-center",
      "pathology-lab",
      "diagnostic-lab",
      "diagnostic-services",
      "medical-diagnostics",
      "diagnostic-imaging",
      "medical-imaging",
      "radiology-services",
    ],
  },
  {
    id: "health-checkups",
    title: "Health Checkups & Screening",
    description:
      "Comprehensive health checkup and preventive screening packages including full body checkups, executive wellness programs, corporate health assessments, gender-specific and age-specific screening, cardiac risk evaluation, diabetes screening, and cancer detection packages.",
    icon: "HeartPulse",
    services: [
      "health-checkup",
      "full-body-check-up",
      "master-health-checkup",
      "executive-health-checkup",
      "executive-health-screening",
      "preventive-health-checkup",
      "preventive-health-screening",
      "annual-health-checkup",
      "corporate-health-checkup",
      "employee-health-checkup",
      "pre-employment-health-checkup",
      "wellness-screening",
      "health-screening",
      "women-health-checkup",
      "women-health-screening",
      "men-health-checkup",
      "men-health-screening",
      "senior-citizen-health-checkup",
      "senior-health-checkup",
      "family-health-checkup",
      "heart-health-checkup",
      "cardiac-health-checkup",
      "diabetes-health-checkup",
      "diabetes-health-screening",
      "cancer-screening",
      "cancer-screening-package",
    ],
  },
  {
    id: "pathology",
    title: "Pathology & Lab Tests",
    description:
      "Accurate pathology and clinical laboratory testing including complete blood count (CBC), lipid profile, thyroid panel, liver and kidney function tests, diabetes markers, vitamin assays, hormonal panels, and infectious disease screening. Home blood collection available.",
    icon: "TestTube2",
    services: [
      "blood-test",
      "lab-test",
      "pathology-test",
      "home-blood-collection",
      "cbc-test",
      "lipid-profile",
      "thyroid-test",
      "thyroid-profile",
      "liver-function-test",
      "kidney-function-test",
      "diabetes-test",
      "hba1c-test",
      "vitamin-d-test",
      "vitamin-b12-test",
      "iron-profile",
      "urine-test",
      "stool-test",
      "hormone-test",
      "allergy-test",
      "tumor-marker-test",
      "infection-test",
      "covid-test",
      "dengue-test",
      "malaria-test",
      "typhoid-test",
    ],
  },
  {
    id: "ultrasound",
    title: "Ultrasound & Sonography",
    description:
      "High-resolution ultrasound and sonography services covering abdominal, pelvic, thyroid, breast, musculoskeletal, and soft-tissue imaging. Includes USG-guided procedures such as FNAC and biopsy for precise diagnostic evaluation.",
    icon: "Radio",
    services: [
      "ultrasound",
      "sonography",
      "usg-scan",
      "abdominal-ultrasound",
      "pelvic-ultrasound",
      "abdomen-pelvis-ultrasound",
      "whole-abdomen-ultrasound",
      "whole-abdomen-sonography",
      "upper-abdomen-sonography",
      "lower-abdomen-sonography",
      "kidney-ultrasound",
      "kub-ultrasound",
      "prostate-ultrasound",
      "scrotal-ultrasound",
      "testicular-ultrasound",
      "groin-ultrasound",
      "inguinal-ultrasound",
      "thyroid-ultrasound",
      "breast-ultrasound",
      "neck-ultrasound",
      "neck-sonography",
      "parotid-ultrasound",
      "salivary-gland-ultrasound",
      "axilla-ultrasound",
      "soft-tissue-ultrasound",
      "musculoskeletal-ultrasound",
      "vascular-ultrasound",
      "small-parts-ultrasound",
      "transvaginal-ultrasound",
      "transrectal-ultrasound",
      "guided-ultrasound",
      "guided-fnac",
      "guided-biopsy",
      "ultrasound-guided-procedure",
    ],
  },
  {
    id: "pregnancy",
    title: "Pregnancy & Fetal Medicine",
    description:
      "Specialized pregnancy sonography and fetal medicine services including NT scan, anomaly scan, growth scan, fetal Doppler, fetal echocardiography, biophysical profile, and high-risk pregnancy monitoring across all three trimesters.",
    icon: "Baby",
    services: [
      "pregnancy-sonography",
      "obstetric-ultrasound",
      "early-pregnancy-scan",
      "pregnancy-dating-scan",
      "dating-scan",
      "viability-scan",
      "first-trimester-scan",
      "second-trimester-scan",
      "third-trimester-scan",
      "nt-scan",
      "anomaly-scan",
      "target-scan",
      "targeted-anomaly-scan",
      "level-2-scan",
      "growth-scan",
      "fetal-growth-scan",
      "fetal-wellbeing-scan",
      "fetal-weight-estimation",
      "cervical-length-scan",
      "fetal-doppler",
      "fetal-doppler-study",
      "fetal-echocardiography",
      "fetal-echo",
      "fetal-bpp",
      "biophysical-profile",
      "bpp-scan",
      "high-risk-pregnancy-scan",
      "multiple-pregnancy-scan",
      "twin-pregnancy-scan",
      "antenatal-scan",
      "fetal-medicine-scan",
    ],
  },
  {
    id: "doppler",
    title: "Doppler Studies",
    description:
      "Advanced color Doppler and vascular Doppler studies for arterial, venous, and obstetric evaluations. Includes carotid artery Doppler, renal Doppler, peripheral arterial and venous assessment, deep vein thrombosis (DVT) screening, and uterine/umbilical artery Doppler.",
    icon: "Activity",
    services: [
      "color-doppler",
      "doppler-scan",
      "pregnancy-doppler",
      "obstetric-doppler",
      "arterial-doppler",
      "venous-doppler",
      "vascular-doppler",
      "vascular-color-doppler",
      "carotid-doppler",
      "carotid-artery-doppler",
      "renal-doppler",
      "uterine-artery-doppler",
      "uterine-doppler",
      "umbilical-artery-doppler",
      "middle-cerebral-artery-doppler",
      "lower-limb-doppler",
      "upper-limb-doppler",
      "peripheral-arterial-doppler",
      "venous-insufficiency-scan",
      "deep-vein-thrombosis-scan",
      "dvt-doppler",
    ],
  },
  {
    id: "breast-imaging",
    title: "Breast Imaging",
    description:
      "Advanced breast imaging services including digital mammography, 3D mammography (tomosynthesis), sonomammography, breast cancer screening, and comprehensive breast diagnostics for early detection and monitoring.",
    icon: "Ribbon",
    services: [
      "mammography",
      "digital-mammography",
      "3d-mammography",
      "sonomammography",
      "breast-imaging",
      "breast-screening",
      "breast-cancer-screening",
      "breast-diagnostics",
      "digital-breast-tomosynthesis",
      "3d-breast-imaging",
    ],
  },
  {
    id: "womens-fertility",
    title: "Women's Health & Fertility Services",
    description:
      "Comprehensive women's health and fertility diagnostics including follicular study, fertility monitoring, ovulation tracking, HSG test, SSG test, gynecology ultrasound, and reproductive health screening for family planning and fertility assessment.",
    icon: "Heart",
    services: [
      "follicular-study",
      "fertility-scan",
      "fertility-assessment",
      "fertility-monitoring",
      "ovulation-study",
      "ovulation-monitoring",
      "reproductive-health-screening",
      "gynecology-ultrasound",
      "pelvic-scan-for-fertility",
      "hsg-test",
      "ssg-test",
    ],
  },
  {
    id: "mri",
    title: "MRI Services",
    description:
      "State-of-the-art MRI scanning for brain, spine, joints, abdomen, breast, cardiac, and whole-body imaging. Includes specialized MRI sequences such as MRCP, MR angiography, contrast-enhanced MRI, and MRI screening for early disease detection.",
    icon: "Scan",
    services: [
      "mri-scan",
      "mri-brain",
      "brain-mri",
      "mri-spine",
      "spine-mri",
      "cervical-spine-mri",
      "lumbar-spine-mri",
      "whole-spine-mri",
      "mri-neck",
      "mri-shoulder",
      "shoulder-mri",
      "mri-elbow",
      "mri-wrist",
      "mri-hand",
      "mri-hip",
      "mri-thigh",
      "mri-knee",
      "knee-mri",
      "mri-ankle",
      "mri-foot",
      "mri-joint",
      "pelvis-mri",
      "abdominal-mri",
      "mri-whole-abdomen",
      "breast-mri",
      "cardiac-mri",
      "mri-pituitary",
      "mri-orbit",
      "mri-face",
      "mri-paranasal-sinus",
      "mri-prostate",
      "mri-enterography",
      "mri-mrcp",
      "mrcp-scan",
      "mr-angiography",
      "mri-angiography",
      "whole-body-mri",
      "contrast-mri",
      "mri-brain-screening",
    ],
  },
  {
    id: "ct-scan",
    title: "CT Scan Services",
    description:
      "High-resolution CT scan services including HRCT chest, brain CT, CT angiography, coronary CT angiography, CT-guided biopsy, whole-body CT, low-dose CT for lung cancer screening, and CT colonography/enterography for GI evaluation.",
    icon: "CircleDot",
    services: [
      "ct-scan",
      "hrct-scan",
      "hrct-chest",
      "ct-brain",
      "brain-ct-scan",
      "ct-neck",
      "ct-face",
      "ct-orbit",
      "ct-pns",
      "ct-temporal-bone",
      "ct-spine",
      "chest-ct-scan",
      "abdomen-ct-scan",
      "ct-abdomen-pelvis",
      "ct-kub",
      "cardiac-ct-scan",
      "ct-angiography",
      "coronary-ct-angiography",
      "ct-coronary-angiography",
      "ct-pulmonary-angiography",
      "ct-enterography",
      "ct-colonography",
      "ct-urology",
      "ct-guided-biopsy",
      "ct-guided-fnac",
      "whole-body-ct-scan",
      "contrast-ct-scan",
      "low-dose-ct",
      "lung-cancer-screening-ct",
    ],
  },
  {
    id: "pet-ct",
    title: "PET CT & Nuclear Medicine",
    description:
      "PET CT scanning and nuclear medicine services for oncology, cardiology, and neurology. Includes whole-body PET CT, FDG PET CT, bone scintigraphy, thyroid scan, renal scan (DTPA/EC/MAG3), SPECT imaging, myocardial perfusion scan, and GFR estimation.",
    icon: "Atom",
    services: [
      "pet-scan",
      "pet-ct",
      "whole-body-pet-ct",
      "whole-body-pet-scan",
      "fdg-pet-ct",
      "oncology-pet-ct",
      "cardiac-pet-ct",
      "neurology-pet-ct",
      "cancer-pet-scan",
      "pet-cancer-screening",
      "spect-scan",
      "nuclear-medicine",
      "dtpa-scan",
      "ec-scan",
      "renal-scan",
      "renal-function-scan",
      "ec-renal-scan",
      "mag3-scan",
      "bone-scan",
      "bone-scintigraphy",
      "thyroid-scan",
      "thyroid-scintigraphy",
      "thyroid-uptake-scan",
      "parathyroid-scan",
      "gfr-test",
      "myocardial-perfusion-scan",
      "lung-perfusion-scan",
      "gastric-emptying-study",
      "hepatobiliary-scan",
      "fapi-pet-ct",
      "fapi-pet-scan",
      "dota-pet-ct",
      "dota-pet-scan",
      "dopa-scan",
      "dopa-pet-ct",
      "psma-pet-scan",
    ],
  },
  {
    id: "bone-health",
    title: "Bone Health & DEXA",
    description:
      "DEXA bone densitometry and bone mineral density (BMD) testing for osteoporosis screening, fracture risk assessment, and monitoring bone health in postmenopausal women, elderly patients, and those on long-term corticosteroid therapy.",
    icon: "Bone",
    services: [
      "dexa-bone-scan",
      "bone-density-test",
      "bmd-test",
      "osteoporosis-screening",
    ],
  },
  {
    id: "cardiology",
    title: "Cardiology Diagnostics",
    description:
      "Complete cardiac diagnostics including ECG, 2D echocardiography, stress echo, TMT (treadmill test), Holter monitoring (24/48/72-hour), ambulatory BP monitoring, cardiac risk assessment, coronary angiography, and interventional cardiology procedures.",
    icon: "HeartPulse",
    services: [
      "ecg",
      "ecg-test",
      "electrocardiogram",
      "2d-echo",
      "2d-echo-test",
      "echo-test",
      "echocardiography",
      "color-echo",
      "stress-echo",
      "dobutamine-stress-echo",
      "tmt-test",
      "stress-test",
      "holter-monitoring",
      "24-hour-holter",
      "48-hour-holter",
      "72-hour-holter",
      "ambulatory-ecg",
      "ambulatory-bp-monitoring",
      "bp-monitoring",
      "24-hour-bp-monitoring",
      "heart-screening",
      "cardiac-screening",
      "cardiac-risk-assessment",
      "cardiac-evaluation",
      "angiography",
      "coronary-angiography",
      "angioplasty",
      "tavr",
      "cardiac-catheterization",
    ],
  },
  {
    id: "liver",
    title: "Liver & Fibroscan",
    description:
      "Advanced liver diagnostics including FibroScan (transient elastography), liver stiffness measurement, fatty liver assessment, liver fibrosis staging, cirrhosis screening, and comprehensive chronic liver disease evaluation for NAFLD/NASH patients.",
    icon: "Stethoscope",
    services: [
      "fibroscan",
      "fibroscan-test",
      "liver-fibroscan",
      "liver-elastography",
      "hepatic-elastography",
      "fatty-liver-assessment",
      "fatty-liver-screening",
      "fatty-liver-scan",
      "liver-health-assessment",
      "liver-screening",
      "liver-fibrosis-assessment",
      "liver-stiffness-test",
      "cirrhosis-screening",
      "chronic-liver-disease-screening",
    ],
  },
  {
    id: "genetics",
    title: "Genetic Testing",
    description:
      "Comprehensive genetic testing services including NIPT (non-invasive prenatal testing), karyotyping, chromosomal analysis, carrier screening, DNA analysis, paternity testing, molecular diagnostics, cytogenetics, and reproductive genetics for fertility and prenatal care.",
    icon: "Dna",
    services: [
      "prenatal-test",
      "prenatal-genetic-testing",
      "nipt-test",
      "nips-test",
      "nippt",
      "karyotype-test",
      "chromosomal-analysis",
      "chromosomal-testing",
      "chromosome-analysis",
      "genetic-test",
      "genetic-screening",
      "genetic-counselling",
      "genetic-counselling-service",
      "carrier-screening",
      "carrier-testing",
      "dna-test",
      "dna-analysis",
      "paternity-test",
      "relationship-dna-test",
      "molecular-diagnostics",
      "cytogenetics",
      "fertility-genetic-test",
      "fertility-genetic-screening",
      "reproductive-genetics",
      "fetal-genetic-testing",
    ],
  },
  {
    id: "genomic-sequencing",
    title: "Genomic Sequencing",
    description:
      "Advanced genomic sequencing services including whole exome sequencing (WES), whole genome sequencing (WGS), clinical exome, targeted gene panels, next-generation sequencing (NGS), RNA sequencing, liquid biopsy NGS, and somatic/germline tumor sequencing for precision medicine.",
    icon: "Dna",
    services: [
      "whole-exome-sequencing",
      "whole-genome-sequencing",
      "clinical-exome-sequencing",
      "targeted-gene-panel",
      "next-generation-sequencing",
      "trio-whole-exome-sequencing",
      "rna-sequencing",
      "transcriptome-sequencing",
      "exome-plus-sequencing",
      "mitochondrial-genome-sequencing",
      "long-read-genome-sequencing",
      "copy-number-variation-analysis",
      "chromosomal-microarray",
      "whole-transcriptome-sequencing",
      "metagenomic-sequencing",
      "16s-rrna-sequencing",
      "cell-free-dna-sequencing",
      "liquid-biopsy-ngs",
      "somatic-tumor-sequencing",
      "germline-sequencing",
    ],
  },
  {
    id: "microbiome",
    title: "Microbiome Testing",
    description:
      "Comprehensive gut microbiome testing and analysis services including stool microbiome sequencing, 16S rRNA analysis, metagenomic profiling, gut dysbiosis evaluation, gut flora mapping, and microbiome DNA sequencing for digestive health assessment.",
    icon: "Bug",
    services: [
      "gut-microbiome-test",
      "gut-health-test",
      "stool-microbiome-analysis",
      "16s-rrna-sequencing",
      "metagenomic-sequencing",
      "gut-dysbiosis-test",
      "gut-flora-analysis",
      "microbiome-dna-sequencing",
    ],
  },
  {
    id: "urology",
    title: "Urology Diagnostics",
    description:
      "Specialized urodynamic studies and urology diagnostics including uroflowmetry, cystometry, pressure-flow study, video urodynamics, post-void residual measurement, urethral pressure profiling, leak point pressure testing, and pelvic floor EMG for bladder and urinary tract evaluation.",
    icon: "Droplets",
    services: [
      "uroflowmetry",
      "urodynamic-study",
      "complete-urodynamic-study",
      "video-urodynamic-study",
      "cystometry",
      "pressure-flow-study",
      "post-void-residual-urine",
      "urethral-pressure-profile",
      "leak-point-pressure-test",
      "pelvic-floor-electromyography",
    ],
  },
  {
    id: "ambulance",
    title: "Ambulance Services",
    description:
      "24x7 emergency and non-emergency ambulance services including ICU ambulance, ALS/BLS ambulance, ventilator ambulance, cardiac ambulance, neonatal ambulance, patient transport, hospital transfer, long-distance ambulance, wheelchair ambulance, and mortuary/freezer box services.",
    icon: "Siren",
    services: [
      "emergency-ambulance",
      "24x7-ambulance-service",
      "ambulance-booking",
      "icu-ambulance",
      "als-ambulance",
      "bls-ambulance",
      "ventilator-ambulance",
      "cardiac-ambulance",
      "oxygen-ambulance",
      "neonatal-ambulance",
      "pediatric-ambulance",
      "patient-transport-ambulance",
      "hospital-transfer-ambulance",
      "long-distance-ambulance",
      "wheelchair-ambulance",
      "stretcher-ambulance",
      "air-ambulance",
      "event-medical-ambulance",
      "dead-body-ambulance",
      "mortuary-ambulance",
      "freezer-box-service",
    ],
  },
];

export function getCategoryForService(
  serviceSlug: string
): ServiceCategory | undefined {
  return SERVICE_CATEGORIES.find((cat) => cat.services.includes(serviceSlug));
}

export function getCategoryById(
  categoryId: string
): ServiceCategory | undefined {
  return SERVICE_CATEGORIES.find((cat) => cat.id === categoryId);
}
