// Google Merchant Center & High-Authority Product Configuration
// Optimized for AEO (Answer Engine Optimization), SEO (Search Engine Optimization),
// GEO (Generative Engine Optimization), LLMO (Large Language Model Optimization), and SMO.
// Includes complete Pre-Requisites, Fasting Guidelines, Reporting Timeframes, and Appointment Booking Processes.

export interface GMCProduct {
  id: string;
  title: string;
  description: string;
  price: number;        // Discounted/Sale price
  mrp: number;          // Original MRP
  currency: string;
  imageUrl: string;
  category: string;
  slug: string;         // URL slug for landing page
  serviceSlug: string;  // Links to main service page
  availability: string;
  condition: string;
  brand: string;
  googleProductCategory: string;

  // Rich AEO / GEO / SEO / LLMO Metadata Fields
  prerequisites: string;
  fastingGuidelines: string;
  reportingTime: string;
  bookingProcess: string;
}

export const GMC_PRODUCTS: GMCProduct[] = [
  {
    id: "HENO-MRI-001",
    title: "3.0T High-Field MRI Brain Scan",
    description: "High-resolution 3.0 Tesla magnetic resonance neuroimaging delivering sub-millimeter 3D tissue contrast of brain parenchyma, cranial nerves, ventricular system, and cerebral vasculature. Provides essential diagnostic evaluation for persistent headaches, acute stroke risk, intracranial lesions, seizures, white matter diseases, and structural cerebral abnormalities.",
    price: 6500,
    mrp: 7000,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/MRI%20SCAN/Service/Service-GMC/3t-mri-scan-cbd-belapur-henotic-diagnostics_service.webp",
    category: "MRI Diagnostics",
    slug: "mri-brain-plain",
    serviceSlug: "mri-brain",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "Doctor prescription required. Metallic objects, jewelry, implants, and hearing aids must be removed before entering the 3.0T magnet room. Inform technologist of any pacemakers or metallic clips.",
    fastingGuidelines: "No fasting required for Plain MRI Brain. 4 hours fasting recommended if contrast enhancement is advised by physician.",
    reportingTime: "Same-day digital report within 6-8 hours via WhatsApp and PDF download portal. HD Film print available upon request.",
    bookingProcess: "Instant online booking via Henotic Diagnostics portal -> Instant SMS/WhatsApp Voucher -> Priority access at NABL facility.",
  },
  {
    id: "HENO-CT-001",
    title: "128-Slice Ultra-Low Dose CT Brain Scan",
    description: "Ultra-fast 128-slice multi-detector computed tomography providing rapid sub-second cross-sectional brain imaging with advanced dose-reduction technology. Delivers immediate diagnostic clarity for acute intracranial hemorrhage, skull trauma, ischemic cerebrovascular injury, mass lesions, and paranasal sinus pathologies.",
    price: 4500,
    mrp: 5000,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/MRI%20SCAN/Service/Service-GMC/diagnostic-mri-center-seawoods-henotic-diagnostics_service.webp",
    category: "CT Diagnostic Imaging",
    slug: "ct-brain-plain",
    serviceSlug: "ct-brain",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "Doctor prescription required. Remove head jewelry, hairpins, hearing aids, and metallic items.",
    fastingGuidelines: "No fasting needed for Plain CT Brain. 4 hours fasting for Contrast CT Brain.",
    reportingTime: "Same-day express report within 4-6 hours delivered digitally via WhatsApp & Email.",
    bookingProcess: "Book online in 30 seconds -> Receive confirmation voucher -> Fast-track scan at center.",
  },
  {
    id: "HENO-PET-001",
    title: "18F-FDG Whole Body PET-CT Molecular Scan",
    description: "Advanced 18F-FDG Positron Emission Tomography co-registered with high-resolution 128-slice CT for anatomical and metabolic cancer evaluation. Quantifies cellular glucose metabolism across all organ systems to support early oncological detection, precise tumor staging, treatment response monitoring, and recurrence surveillance.",
    price: 14000,
    mrp: 16000,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PET-CT/pet-ct-scan-roadpali-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Molecular PET-CT Imaging",
    slug: "pet-ct-whole-body",
    serviceSlug: "pet-ct-scan",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "Doctor prescription & prior medical records mandatory. Serum creatinine & fasting blood glucose testing conducted before scan.",
    fastingGuidelines: "Strict 6 hours overnight fasting. Avoid carbohydrate-rich food, sugar, caffeine, and heavy physical exercise 24 hours before scan. Plain water encouraged.",
    reportingTime: "Detailed super-specialist report delivered within 12-24 hours digitally via WhatsApp and Email.",
    bookingProcess: "Online slot reservation -> Clinical radiotracer scheduling confirmation -> Dedicated scan appointment.",
  },
  {
    id: "HENO-PATH-001",
    title: "CBC Complete Blood Count Test",
    description: "Comprehensive 24-parameter automated hematology blood assay measuring Hemoglobin, Red Blood Cells, Leukocytes, Platelets, Hematocrit, and Differential Counts. Serves as the core clinical baseline for identifying anemia, systemic infections, inflammatory states, immune conditions, and hematologic disorders.",
    price: 250,
    mrp: 350,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PATHOLOGY/blood-test-center-vashi-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Hematology Pathology",
    slug: "cbc-test",
    serviceSlug: "blood-test",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "No prescription required for routine checkup. Open for all age groups.",
    fastingGuidelines: "Non-fasting test. Sample can be collected anytime during day or evening.",
    reportingTime: "Same-day express report within 4-6 hours via WhatsApp & Email PDF.",
    bookingProcess: "Select doorstep time slot -> Phlebotomist arrives with sterile kit -> Digital report on WhatsApp.",
  },
  {
    id: "HENO-PATH-002",
    title: "HbA1c Glycated Hemoglobin Test",
    description: "Gold-standard High-Performance Liquid Chromatography (HPLC) assay quantifying glycated hemoglobin levels to evaluate 3-month average blood glucose control. Essential for definitive diabetes diagnosis, prediabetes risk classification, and long-term glycemic management.",
    price: 550,
    mrp: 750,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PATHOLOGY/blood-test-center-vashi-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Endocrine Pathology",
    slug: "hba1c-test",
    serviceSlug: "blood-test",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "No prescription necessary. Suitable for routine diabetes screening and monitoring.",
    fastingGuidelines: "No fasting required. Can be conducted anytime regardless of food intake.",
    reportingTime: "Same-day digital report within 4-6 hours via WhatsApp & Email.",
    bookingProcess: "Book home visit online -> Doorstep blood draw by certified phlebotomist -> Instant digital report.",
  },
  {
    id: "HENO-PATH-003",
    title: "hs-CRP High Sensitivity C-Reactive Protein Test",
    description: "High-sensitivity immunoturbidimetric assay measuring ultra-low levels of vascular and systemic inflammation. Crucial biomarker for cardiovascular risk stratification, arterial plaque inflammatory assessment, and tracking subclinical autoimmune or inflammatory conditions.",
    price: 500,
    mrp: 700,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PATHOLOGY/blood-test-center-vashi-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Cardiovascular Pathology",
    slug: "crp-test",
    serviceSlug: "blood-test",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "No prescription needed. Avoid heavy physical exertion 12 hours prior.",
    fastingGuidelines: "8 hours overnight fasting recommended for baseline accuracy; plain water allowed.",
    reportingTime: "Same-day digital report within 4-6 hours via WhatsApp & Email.",
    bookingProcess: "Schedule home visit online -> Cold-chain doorstep blood collection -> WhatsApp report delivery.",
  },
  {
    id: "HENO-MAMMO-001",
    title: "Full-Field Digital Mammography Scan",
    description: "High-definition Full-Field Digital Mammography (FFDM) providing low-radiation tissue visualization for early breast screening, microcalcification detection, and architectural distortion analysis in dense breast tissue.",
    price: 3000,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/MAMMOGRAPHY/digital-mammogram-cbd-belapur-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Breast Diagnostic Imaging",
    slug: "digital-mammography",
    serviceSlug: "mammography",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "Best scheduled 7-10 days after menstruation. Do not use deodorants, talcum powders, or lotions on upper body on test day.",
    fastingGuidelines: "No fasting required. Normal dietary intake permitted.",
    reportingTime: "Same-day digital report within 6-8 hours with female radiologist signature.",
    bookingProcess: "Select online appointment slot -> Female staff guided room -> Instant WhatsApp digital report.",
  },
  {
    id: "HENO-DEXA-001",
    title: "Whole Body BMD DEXA Bone Density Scan",
    description: "Central Dual-Energy X-ray Absorptiometry (DEXA) providing accurate quantification of Bone Mineral Density (BMD), T-scores, and Z-scores across the lumbar spine and hip regions for osteoporosis assessment and fracture risk evaluation.",
    price: 4000,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/DEXA/bmd-dexa-scan-kharghar-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Bone Densitometry",
    slug: "bmd-dexa-scan",
    serviceSlug: "bone-density",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "Discontinue calcium supplements 24 hours prior to scan. Wear clothing without metal fasteners or snaps.",
    fastingGuidelines: "No fasting required.",
    reportingTime: "Express digital report within 4-6 hours with T-score & Z-score charts.",
    bookingProcess: "Book voucher online -> Fast 15-minute DEXA scan -> Digital report on WhatsApp.",
  },
  {
    id: "HENO-USG-001",
    title: "Prenatal NT Nuchal Translucency Ultrasound Scan",
    description: "First-trimester (11 to 13.6 weeks) high-resolution screening sonogram evaluating fetal nuchal translucency thickness and nasal bone presence for early chromosomal anomaly assessment and developmental monitoring.",
    price: 3000,
    mrp: 4500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/nt-scan-belapur-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Fetal Diagnostic Sonography",
    slug: "nt-scan",
    serviceSlug: "nt-scan",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "Doctor prescription, ID proof (Aadhaar/PAN), & previous USG reports mandatory for PCPNDT Form F compliance.",
    fastingGuidelines: "No fasting required. Maintain moderately full bladder if advised by technologist.",
    reportingTime: "Immediate report & thermal prints provided post-scan; digital copy via WhatsApp within 2 hours.",
    bookingProcess: "Select gestational week slot -> Submit PCPNDT registration details -> Expert 4D sonography scan.",
  },
  {
    id: "HENO-USG-002",
    title: "Level-2 Detailed Prenatal Anomaly Ultrasound Scan",
    description: "Targeted second-trimester (18 to 22 weeks) detailed fetal anatomical sonogram evaluating intracranial structures, cardiac 4-chamber anatomy, spinal alignment, facial features, renal systems, and placental positioning.",
    price: 4500,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/pregnancy-anomaly-scan-koparkhairane-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Fetal Diagnostic Sonography",
    slug: "anomaly-scan",
    serviceSlug: "anomaly-scan",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "Doctor prescription, photo ID, & previous pregnancy file mandatory (PCPNDT compliant).",
    fastingGuidelines: "No fasting required. Light meal or juice 30 minutes before scan helps fetal activity.",
    reportingTime: "Digital report & HD 4D images delivered within 2-4 hours on WhatsApp.",
    bookingProcess: "Schedule 18-22 week slot online -> Complete Form F registration -> Comprehensive 4D sonography.",
  },
  {
    id: "HENO-USG-003",
    title: "Abdomen & Pelvis Ultrasound (USG) Scan",
    description: "Comprehensive multi-organ ultrasonography evaluating the liver, gallbladder, kidneys, pancreas, spleen, urinary bladder, uterus, ovaries, and prostate for abdominal pain, gallstones, renal calculi, and visceral pathologies.",
    price: 2000,
    mrp: 2500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/ultrasound-scan-roadpali-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Abdominal Sonography",
    slug: "abdomen-ultrasound",
    serviceSlug: "ultrasound",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "Doctor prescription recommended. Full bladder required for pelvic evaluation.",
    fastingGuidelines: "6-8 hours fasting required for upper abdomen imaging. Drink 1 liter water 1 hr before scan.",
    reportingTime: "Same-day digital report within 2-4 hours via WhatsApp & Email.",
    bookingProcess: "Select morning slot online -> Drink water for full bladder -> Quick 15-minute ultrasound.",
  },
  {
    id: "HENO-USG-004",
    title: "Prenatal Fetal 2D Echocardiography Scan",
    description: "Specialized fetal cardiac ultrasound and Color Doppler analysis evaluating fetal heart chamber structure, valvular function, great vessel outflow tracts, and cardiac rhythm during high-risk pregnancy evaluations.",
    price: 4000,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/fetal-2d-echo-scan-kamothe-henotic-diagnostics_service.webp",
    category: "Fetal Cardiology",
    slug: "fetal-2d-echo",
    serviceSlug: "fetal-echo",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "Doctor prescription & Level-2 anomaly scan report mandatory (PCPNDT Form F compliant).",
    fastingGuidelines: "No fasting required.",
    reportingTime: "Express digital report within 2-4 hours with color doppler cardiac measurements.",
    bookingProcess: "Book 18-24 week slot online -> Submit medical prescription -> Specialist fetal echo examination.",
  },
  {
    id: "HENO-ECHO-001",
    title: "Cardiac 2D Echo Color Doppler Scan",
    description: "Transthoracic 2D Echocardiography with Color Doppler assessing cardiac chamber dimensions, left ventricular Ejection Fraction (EF %), valvular hemodynamics, and wall motion for heart failure and ischemic heart disease evaluation.",
    price: 2700,
    mrp: 3500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/ECHO/2d-echo-test-henotic-diagnostics_service.webp",
    category: "Cardiology Imaging",
    slug: "2d-echo-test",
    serviceSlug: "2d-echo",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
    prerequisites: "Doctor prescription recommended. Carry past ECG or cardiac reports if available.",
    fastingGuidelines: "No fasting required. Take prescribed daily medications normally.",
    reportingTime: "Cardiologist signed digital report within 2-4 hours on WhatsApp & PDF portal.",
    bookingProcess: "Book slot online -> Non-invasive 20-min Doppler scan -> Instant digital report on WhatsApp.",
  },
];

export function getGMCProduct(slug: string): GMCProduct | undefined {
  return GMC_PRODUCTS.find(p => p.slug === slug);
}
