// Google Merchant Center Product Configuration
// All prices in INR (₹)
// IMPORTANT: Descriptions are intentionally facility/equipment-focused (NOT condition-focused)
// to comply with Google's Personalized Advertising policy for health content.

export interface GMCProduct {
  id: string;
  title: string;
  description: string;
  price: number;        // Discounted/Sale price
  mrp: number;          // Original MRP
  currency: string;
  imageUrl: string;
  category: string;
  slug: string;         // URL slug for landing page
  serviceSlug: string;  // Links to main service page
  availability: string;
  condition: string;
  brand: string;
  googleProductCategory: string;
}

export const GMC_PRODUCTS: GMCProduct[] = [
  {
    id: "HENO-MRI-001",
    title: "MRI Brain Plain Scan",
    description: "3.0 Tesla MRI Brain Plain Scan at Henotic Diagnostics, Kharghar, Navi Mumbai. NABL and ISO accredited imaging center. Same-day digital reports. Walk-in and appointment available.",
    price: 6500,
    mrp: 7000,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/MRI%20SCAN/Service/Service-GMC/3t-mri-scan-cbd-belapur-henotic-diagnostics_service.webp",
    category: "MRI",
    slug: "mri-brain-plain",
    serviceSlug: "mri-brain",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-CT-001",
    title: "CT Brain Plain Scan",
    description: "128-slice CT Brain Plain Scan at Henotic Diagnostics, Kharghar, Navi Mumbai. Low-dose technology. NABL accredited center. Same-day digital reports with expert review.",
    price: 4500,
    mrp: 5000,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/MRI%20SCAN/Service/Service-GMC/diagnostic-mri-center-seawoods-henotic-diagnostics_service.webp",
    category: "CT Scan",
    slug: "ct-brain-plain",
    serviceSlug: "ct-brain",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-PET-001",
    title: "18FDG Whole Body PET-CT Scan",
    description: "18FDG Whole Body PET-CT Scan at Henotic Diagnostics, Navi Mumbai. Digital PET-CT with advanced fusion imaging technology. NABL and ISO accredited diagnostic center.",
    price: 14000,
    mrp: 16000,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PET-CT/pet-ct-scan-roadpali-navi-mumbai-henotic-diagnostics_service.webp",
    category: "PET-CT",
    slug: "pet-ct-whole-body",
    serviceSlug: "pet-ct-scan",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-PATH-001",
    title: "CBC Complete Blood Count",
    description: "Complete Blood Count test at Henotic Diagnostics, Kharghar, Navi Mumbai. Fully automated hematology analyzer. NABL accredited pathology lab. Reports via WhatsApp.",
    price: 250,
    mrp: 350,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PATHOLOGY/blood-test-center-vashi-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Pathology",
    slug: "cbc-test",
    serviceSlug: "blood-test",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-PATH-002",
    title: "HBA1C Glycated Hemoglobin Test",
    description: "HBA1C test at Henotic Diagnostics, Kharghar, Navi Mumbai. High-precision automated analyzer. NABL accredited pathology lab. Same-day digital reports available.",
    price: 550,
    mrp: 750,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PATHOLOGY/blood-test-center-vashi-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Pathology",
    slug: "hba1c-test",
    serviceSlug: "blood-test",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-PATH-003",
    title: "CRP C-Reactive Protein Test",
    description: "CRP test at Henotic Diagnostics, Kharghar, Navi Mumbai. Automated biochemistry analyzer. NABL accredited laboratory. Quick turnaround with digital reports.",
    price: 500,
    mrp: 700,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PATHOLOGY/blood-test-center-vashi-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Pathology",
    slug: "crp-test",
    serviceSlug: "blood-test",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-MAMMO-001",
    title: "Digital Mammography",
    description: "Full-field digital mammography at Henotic Diagnostics, Navi Mumbai. Advanced imaging equipment with dedicated suite. NABL and ISO accredited. Female staff available.",
    price: 3000,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/MAMMOGRAPHY/digital-mammogram-cbd-belapur-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Imaging",
    slug: "digital-mammography",
    serviceSlug: "mammography",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-DEXA-001",
    title: "BMD DEXA Scan",
    description: "DEXA bone mineral density scan at Henotic Diagnostics, Kharghar, Navi Mumbai. Dual-energy X-ray absorptiometry equipment. NABL accredited. Reports with T-score included.",
    price: 4000,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/DEXA/bmd-dexa-scan-kharghar-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Imaging",
    slug: "bmd-dexa-scan",
    serviceSlug: "bone-density",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-USG-001",
    title: "NT Scan Ultrasound",
    description: "NT Scan ultrasound at Henotic Diagnostics, Navi Mumbai. High-resolution ultrasound equipment. NABL accredited center. Appointment and walk-in available.",
    price: 3000,
    mrp: 4500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/nt-scan-belapur-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Sonography",
    slug: "nt-scan",
    serviceSlug: "nt-scan",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-USG-002",
    title: "Anomaly Scan Ultrasound",
    description: "Level 2 anomaly scan ultrasound at Henotic Diagnostics, Navi Mumbai. High-resolution 4D ultrasound equipment. NABL accredited center. Expert sonologist on-site.",
    price: 4500,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/pregnancy-anomaly-scan-koparkhairane-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Sonography",
    slug: "anomaly-scan",
    serviceSlug: "anomaly-scan",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-USG-003",
    title: "Abdomen Ultrasound Scan",
    description: "Abdomen ultrasound scan at Henotic Diagnostics, Kharghar, Navi Mumbai. Real-time imaging with latest ultrasound equipment. NABL accredited. Same-day report available.",
    price: 2000,
    mrp: 2500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/ultrasound-scan-roadpali-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Sonography",
    slug: "abdomen-ultrasound",
    serviceSlug: "ultrasound",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-USG-004",
    title: "Fetal 2D Echocardiography",
    description: "Fetal 2D Echo scan at Henotic Diagnostics, Navi Mumbai. Advanced echocardiography equipment with expert review. NABL and ISO accredited imaging center.",
    price: 4000,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/fetal-2d-echo-scan-kamothe-henotic-diagnostics_service.webp",
    category: "Sonography",
    slug: "fetal-2d-echo",
    serviceSlug: "fetal-echo",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
  {
    id: "HENO-ECHO-001",
    title: "2D Echo Echocardiography",
    description: "2D Echocardiography with Color Doppler at Henotic Diagnostics, Kharghar, Navi Mumbai. Advanced cardiac imaging equipment. NABL accredited. Walk-in and appointment available.",
    price: 2700,
    mrp: 3500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/ECHO/2d-echo-test-henotic-diagnostics_service.webp",
    category: "Cardiology",
    slug: "2d-echo-test",
    serviceSlug: "2d-echo",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "2915",
  },
];

export function getGMCProduct(slug: string): GMCProduct | undefined {
  return GMC_PRODUCTS.find(p => p.slug === slug);
}
