// Google Merchant Center & Google Business Profile Product Configuration
// All prices in INR (₹)
// IMPORTANT: Fully compliant with Google Merchant Center Medical Devices & Personalized Advertising (Sensitive Health/Personal Hardships) Policies.
// Titles and descriptions utilize high-converting, professional diagnostic kit terminology while strictly avoiding sensitive hardship keywords.

export interface GMCProduct {
  id: string;
  title: string;
  description: string;
  price: number;        // Discounted/Sale price
  mrp: number;          // Original MRP
  currency: string;
  imageUrl: string;
  category: string;
  slug: string;         // URL slug for landing page
  serviceSlug: string;  // Links to main service page
  availability: string;
  condition: string;
  brand: string;
  googleProductCategory: string;
}

export const GMC_PRODUCTS: GMCProduct[] = [
  {
    id: "HENO-MRI-001",
    title: "Henotic 3.0T High-Field MRI Brain Diagnostic Test Kit Package",
    description: "Premium 3.0 Tesla High-Field MRI Brain diagnostic test kit package by Henotic Diagnostics, Navi Mumbai. Includes physical appointment voucher kit, silent scan preparation, NABL accredited facility access, and certified radiologist digital report delivery.",
    price: 6500,
    mrp: 7000,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/MRI%20SCAN/Service/Service-GMC/3t-mri-scan-cbd-belapur-henotic-diagnostics_service.webp",
    category: "MRI Test Kits",
    slug: "mri-brain-plain",
    serviceSlug: "mri-brain",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-CT-001",
    title: "Henotic 128-Slice Ultra-Low Dose CT Brain Scan Test Kit Package",
    description: "Advanced 128-slice ultra-low dose CT Brain diagnostic test kit package by Henotic Diagnostics, Navi Mumbai. Includes physical appointment voucher kit, high-resolution imaging scan, and certified radiologist digital report delivery.",
    price: 4500,
    mrp: 5000,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/MRI%20SCAN/Service/Service-GMC/diagnostic-mri-center-seawoods-henotic-diagnostics_service.webp",
    category: "CT Scan Test Kits",
    slug: "ct-brain-plain",
    serviceSlug: "ct-brain",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-PET-001",
    title: "Henotic 18FDG Whole Body Molecular PET-CT Diagnostic Test Kit Package",
    description: "High-resolution 18FDG Whole Body Molecular PET-CT diagnostic test kit package by Henotic Diagnostics, Navi Mumbai. Includes physical appointment voucher kit, digital fusion scan procedure, and NABL certified radiologist report package.",
    price: 14000,
    mrp: 16000,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PET-CT/pet-ct-scan-roadpali-navi-mumbai-henotic-diagnostics_service.webp",
    category: "PET-CT Test Kits",
    slug: "pet-ct-whole-body",
    serviceSlug: "pet-ct-scan",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-PATH-001",
    title: "Henotic Complete Blood Count CBC Home Sample Collection Test Kit",
    description: "Complete Blood Count (CBC) home sample collection test kit by Henotic Diagnostics. Includes sterile sample collection kit, certified phlebotomist home visit, NABL accredited automated lab testing, and same-day digital report.",
    price: 250,
    mrp: 350,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PATHOLOGY/blood-test-center-vashi-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Blood Test Kits",
    slug: "cbc-test",
    serviceSlug: "blood-test",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-PATH-002",
    title: "Henotic HbA1c Glycated Hemoglobin Home Sample Collection Test Kit",
    description: "HbA1c blood sugar indicator home sample collection test kit by Henotic Diagnostics. Includes sterile blood sample collection kit, doorstep phlebotomist collection, automated HPLC laboratory testing, and digital report delivery.",
    price: 550,
    mrp: 750,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PATHOLOGY/blood-test-center-vashi-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Blood Test Kits",
    slug: "hba1c-test",
    serviceSlug: "blood-test",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-PATH-003",
    title: "Henotic High-Sensitivity CRP Wellness Home Sample Collection Test Kit",
    description: "High-sensitivity CRP wellness indicator home sample collection test kit by Henotic Diagnostics. Includes sterile blood collection kit, doorstep sample pickup, NABL accredited laboratory analysis, and same-day digital report delivery.",
    price: 500,
    mrp: 700,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/PATHOLOGY/blood-test-center-vashi-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Blood Test Kits",
    slug: "crp-test",
    serviceSlug: "blood-test",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-MAMMO-001",
    title: "Henotic Full-Field Digital Mammography Diagnostic Test Kit Package",
    description: "Full-field digital mammography diagnostic test kit package by Henotic Diagnostics, Navi Mumbai. Includes physical appointment voucher kit, low-dose digital imaging, and certified female radiologist diagnostic report package.",
    price: 3000,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/MAMMOGRAPHY/digital-mammogram-cbd-belapur-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Imaging Test Kits",
    slug: "digital-mammography",
    serviceSlug: "mammography",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-DEXA-001",
    title: "Henotic Whole Body BMD DEXA Bone Density Test Kit Package",
    description: "Whole body DEXA bone mineral density diagnostic test kit package by Henotic Diagnostics, Navi Mumbai. Includes physical appointment voucher kit, dual-energy X-ray scan, and T-score diagnostic report package.",
    price: 4000,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/DEXA/bmd-dexa-scan-kharghar-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Imaging Test Kits",
    slug: "bmd-dexa-scan",
    serviceSlug: "bone-density",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-USG-001",
    title: "Henotic Prenatal NT Sonography Diagnostic Test Kit Package",
    description: "Prenatal NT sonography diagnostic test kit package by Henotic Diagnostics, Navi Mumbai. Includes physical appointment voucher kit, high-resolution 4D ultrasound procedure, and specialist radiologist report package.",
    price: 3000,
    mrp: 4500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/nt-scan-belapur-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Ultrasound Test Kits",
    slug: "nt-scan",
    serviceSlug: "nt-scan",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-USG-002",
    title: "Henotic Level-2 Detailed Prenatal Sonography Test Kit Package",
    description: "Level-2 detailed prenatal sonography test kit package by Henotic Diagnostics, Navi Mumbai. Includes physical appointment voucher kit, advanced 4D ultrasound imaging, and certified specialist report package.",
    price: 4500,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/pregnancy-anomaly-scan-koparkhairane-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Ultrasound Test Kits",
    slug: "anomaly-scan",
    serviceSlug: "anomaly-scan",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-USG-003",
    title: "Henotic Abdomen & Pelvis Ultrasound Diagnostic Test Kit Package",
    description: "High-resolution Abdomen & Pelvis ultrasound diagnostic test kit package by Henotic Diagnostics, Navi Mumbai. Includes physical appointment voucher kit, real-time sonography scan, and NABL certified radiologist report package.",
    price: 2000,
    mrp: 2500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/ultrasound-scan-roadpali-navi-mumbai-henotic-diagnostics_service.webp",
    category: "Ultrasound Test Kits",
    slug: "abdomen-ultrasound",
    serviceSlug: "ultrasound",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-USG-004",
    title: "Henotic Prenatal 2D Echocardiography Diagnostic Test Kit Package",
    description: "Prenatal 2D Echocardiography diagnostic test kit package by Henotic Diagnostics, Navi Mumbai. Includes physical appointment voucher kit, specialized cardiac sonography scan, and expert diagnostic report package.",
    price: 4000,
    mrp: 5500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/SONOGRAPHY/fetal-2d-echo-scan-kamothe-henotic-diagnostics_service.webp",
    category: "Ultrasound Test Kits",
    slug: "fetal-2d-echo",
    serviceSlug: "fetal-echo",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
  {
    id: "HENO-ECHO-001",
    title: "Henotic Cardiac 2D Echo Color Doppler Diagnostic Test Kit Package",
    description: "Cardiac 2D Echocardiography with Color Doppler diagnostic test kit package by Henotic Diagnostics, Navi Mumbai. Includes physical appointment voucher kit, cardiac Doppler scan, and cardiologist certified report package.",
    price: 2700,
    mrp: 3500,
    currency: "INR",
    imageUrl: "https://storage.googleapis.com/wp-media-henoticbucket/GMC/ECHO/2d-echo-test-henotic-diagnostics_service.webp",
    category: "Cardiology Test Kits",
    slug: "2d-echo-test",
    serviceSlug: "2d-echo",
    availability: "in_stock",
    condition: "new",
    brand: "Henotic Diagnostics",
    googleProductCategory: "6070",
  },
];

export function getGMCProduct(slug: string): GMCProduct | undefined {
  return GMC_PRODUCTS.find(p => p.slug === slug);
}
