export const services = [
  // DIAGNOSTIC CENTER & HEALTH SCREENING
  "diagnostic-center", "medical-imaging-center", "radiology-center", "pathology-lab", "diagnostic-lab", "diagnostic-services", "medical-diagnostics", "diagnostic-imaging", "medical-imaging", "radiology-services", "health-checkup", "full-body-check-up", "master-health-checkup", "executive-health-checkup", "executive-health-screening", "preventive-health-checkup", "preventive-health-screening", "annual-health-checkup", "corporate-health-checkup", "employee-health-checkup", "pre-employment-health-checkup", "wellness-screening", "health-screening", "women-health-checkup", "women-health-screening", "men-health-checkup", "men-health-screening", "senior-citizen-health-checkup", "senior-health-checkup", "family-health-checkup", "heart-health-checkup", "cardiac-health-checkup", "diabetes-health-checkup", "diabetes-health-screening", "cancer-screening", "cancer-screening-package",
  // PATHOLOGY & LAB TESTS
  "blood-test", "lab-test", "pathology-test", "home-blood-collection", "cbc-test", "lipid-profile", "thyroid-test", "thyroid-profile", "liver-function-test", "kidney-function-test", "diabetes-test", "hba1c-test", "vitamin-d-test", "vitamin-b12-test", "iron-profile", "urine-test", "stool-test", "hormone-test", "allergy-test", "tumor-marker-test", "infection-test", "covid-test", "dengue-test", "malaria-test", "typhoid-test",
  // ULTRASOUND & SONOGRAPHY
  "ultrasound", "sonography", "usg-scan", "abdominal-ultrasound", "pelvic-ultrasound", "abdomen-pelvis-ultrasound", "whole-abdomen-ultrasound", "whole-abdomen-sonography", "upper-abdomen-sonography", "lower-abdomen-sonography", "kidney-ultrasound", "kub-ultrasound", "prostate-ultrasound", "scrotal-ultrasound", "testicular-ultrasound", "groin-ultrasound", "inguinal-ultrasound", "thyroid-ultrasound", "breast-ultrasound", "neck-ultrasound", "neck-sonography", "parotid-ultrasound", "salivary-gland-ultrasound", "axilla-ultrasound", "soft-tissue-ultrasound", "musculoskeletal-ultrasound", "vascular-ultrasound", "small-parts-ultrasound", "transvaginal-ultrasound", "transrectal-ultrasound", "guided-ultrasound", "guided-fnac", "guided-biopsy", "ultrasound-guided-procedure",
  // PREGNANCY & FETAL MEDICINE
  "pregnancy-sonography", "obstetric-ultrasound", "early-pregnancy-scan", "pregnancy-dating-scan", "dating-scan", "viability-scan", "first-trimester-scan", "second-trimester-scan", "third-trimester-scan", "nt-scan", "anomaly-scan", "target-scan", "targeted-anomaly-scan", "level-2-scan", "growth-scan", "fetal-growth-scan", "fetal-wellbeing-scan", "fetal-weight-estimation", "cervical-length-scan", "fetal-doppler", "fetal-doppler-study", "fetal-echocardiography", "fetal-echo", "fetal-bpp", "biophysical-profile", "bpp-scan", "high-risk-pregnancy-scan", "multiple-pregnancy-scan", "twin-pregnancy-scan", "antenatal-scan", "fetal-medicine-scan",
  // DOPPLER STUDIES
  "color-doppler", "doppler-scan", "pregnancy-doppler", "obstetric-doppler", "arterial-doppler", "venous-doppler", "vascular-doppler", "vascular-color-doppler", "carotid-doppler", "carotid-artery-doppler", "renal-doppler", "uterine-artery-doppler", "uterine-doppler", "umbilical-artery-doppler", "middle-cerebral-artery-doppler", "lower-limb-doppler", "upper-limb-doppler", "peripheral-arterial-doppler", "venous-insufficiency-scan", "deep-vein-thrombosis-scan", "dvt-doppler",
  // WOMEN'S HEALTH & BREAST IMAGING
  "mammography", "digital-mammography", "3d-mammography", "sonomammography", "breast-imaging", "breast-screening", "breast-cancer-screening", "breast-diagnostics", "digital-breast-tomosynthesis", "3d-breast-imaging", "follicular-study", "fertility-scan", "fertility-assessment", "fertility-monitoring", "ovulation-study", "ovulation-monitoring", "reproductive-health-screening", "gynecology-ultrasound", "pelvic-scan-for-fertility", "hsg-test", "ssg-test",
  // MRI SERVICES
  "mri-scan", "mri-brain", "brain-mri", "mri-spine", "spine-mri", "cervical-spine-mri", "lumbar-spine-mri", "whole-spine-mri", "mri-neck", "mri-shoulder", "shoulder-mri", "mri-elbow", "mri-wrist", "mri-hand", "mri-hip", "mri-thigh", "mri-knee", "knee-mri", "mri-ankle", "mri-foot", "mri-joint", "pelvis-mri", "abdominal-mri", "mri-whole-abdomen", "breast-mri", "cardiac-mri", "mri-pituitary", "mri-orbit", "mri-face", "mri-paranasal-sinus", "mri-prostate", "mri-enterography", "mri-mrcp", "mrcp-scan", "mr-angiography", "mri-angiography", "whole-body-mri", "contrast-mri", "mri-brain-screening",
  // CT SCAN SERVICES
  "ct-scan", "hrct-scan", "hrct-chest", "ct-brain", "brain-ct-scan", "ct-neck", "ct-face", "ct-orbit", "ct-pns", "ct-temporal-bone", "ct-spine", "chest-ct-scan", "abdomen-ct-scan", "ct-abdomen-pelvis", "ct-kub", "cardiac-ct-scan", "ct-angiography", "coronary-ct-angiography", "ct-coronary-angiography", "ct-pulmonary-angiography", "ct-enterography", "ct-colonography", "ct-urology", "ct-guided-biopsy", "ct-guided-fnac", "whole-body-ct-scan", "contrast-ct-scan", "low-dose-ct", "lung-cancer-screening-ct",
  // PET CT & NUCLEAR MEDICINE
  "pet-scan", "pet-ct", "whole-body-pet-ct", "whole-body-pet-scan", "fdg-pet-ct", "oncology-pet-ct", "cardiac-pet-ct", "neurology-pet-ct", "cancer-pet-scan", "pet-cancer-screening", "spect-scan", "nuclear-medicine", "dtpa-scan", "ec-scan", "renal-scan", "renal-function-scan", "ec-renal-scan", "mag3-scan", "bone-scan", "bone-scintigraphy", "thyroid-scan", "thyroid-scintigraphy", "thyroid-uptake-scan", "parathyroid-scan", "gfr-test", "myocardial-perfusion-scan", "lung-perfusion-scan", "gastric-emptying-study", "hepatobiliary-scan",
  // BONE HEALTH & DEXA
  "dexa-bone-scan", "bone-density-test", "bmd-test", "osteoporosis-screening",
  // CARDIOLOGY DIAGNOSTICS
  "ecg", "ecg-test", "electrocardiogram", "2d-echo", "2d-echo-test", "echo-test", "echocardiography", "color-echo", "stress-echo", "dobutamine-stress-echo", "tmt-test", "stress-test", "holter-monitoring", "24-hour-holter", "48-hour-holter", "72-hour-holter", "ambulatory-ecg", "ambulatory-bp-monitoring", "bp-monitoring", "24-hour-bp-monitoring", "heart-screening", "cardiac-screening", "cardiac-risk-assessment", "cardiac-evaluation",
  // CARDIAC INTERVENTIONS
  "angiography", "coronary-angiography", "angioplasty", "tavr", "cardiac-catheterization",
  // FIBROSCAN & LIVER DIAGNOSTICS
  "fibroscan", "fibroscan-test", "liver-fibroscan", "liver-elastography", "hepatic-elastography", "fatty-liver-assessment", "fatty-liver-screening", "fatty-liver-scan", "liver-health-assessment", "liver-screening", "liver-fibrosis-assessment", "liver-stiffness-test", "cirrhosis-screening", "chronic-liver-disease-screening",
  // GENETIC TESTING
  "prenatal-test", "prenatal-genetic-testing", "nipt-test", "nips-test", "nippt", "karyotype-test", "chromosomal-analysis", "chromosomal-testing", "chromosome-analysis", "genetic-test", "genetic-screening", "genetic-counselling", "genetic-counselling-service", "carrier-screening", "carrier-testing", "dna-test", "dna-analysis", "paternity-test", "relationship-dna-test", "molecular-diagnostics", "cytogenetics", "fertility-genetic-test", "fertility-genetic-screening", "reproductive-genetics", "fetal-genetic-testing"
];